// Normal Window
#define WINDOW_FIRST_XPOS				740
#define WINDOW_SECOND_XPOS				460

// INTRO_ACCOUNT
#define INTRO_ACCOUNT_XPOS				400
#define INTRO_ACCOUNT_YPOS				680
#define INTRO_ACCOUNT_EDIT_MAX_STRING	10

// INTRO_BUTTONSET
#define INTRO_BUTTONSET_XPOS			180
#define INTRO_BUTTONSET_YPOS			680

// INTRO_CHARACTER_SELECT
#define INTRO_CHARACTER_SELECT_XPOS		415
#define INTRO_CHARACTER_SELECT_YPOS		610

// INTRO_WINDOW01
#define INTRO_WINDOW01_XPOS				700
#define INTRO_WINDOW01_YPOS				250

// SMALL_WINDOW_INFO
#define SMALL_WINDOW_INFO_XPOS			400
#define SMALL_WINDOW_INFO_YPOS			0

// MINIMAP_WINDOW
#define MINIMAP_WINDOW_XPOS				0
#define MINIMAP_WINDOW_YPOS				32

// MAIN_FRAME
#define MAIN_FRAME_XPOS					173
#define MAIN_FRAME_YPOS					718
#define MAIN_FRAME_IP_BARTYPE			1

// WINDOW_BUTTON_GROUP
//HO_0413_07 퀵 가이드 업데이트 : 버튼 추가로 인한 시스템 그룹버튼을 전체 길이 142, 버튼당 가로,세로35 테두리는 2로 계산하였음
#define WINDOW_BUTTON_GROUP_XPOS		190//퀵 가이드 버튼 추가로 인한 윈도우 그룹버튼 위치 수정
//#define WINDOW_BUTTON_GROUP_XPOS		51//퀵 가이드 버튼 추가전 위치
#define WINDOW_BUTTON_GROUP_YPOS		681

// SYSTEM_BUTTON_GROUP(기존에는 윈도우 그룹버튼와 시스템 그룹버튼이 동일 라인 이기에 SYSTEM_BUTTON_GROUP_YPOS 없이 WINDOW_BUTTON_GROUP_YPOS를 이용했으나 퀵 가이드 버튼 추가로 인하여 새로 설정해줌)
#define SYSTEM_BUTTON_GROUP_YPOS		645//HO_0413_07 퀵 가이드 업데이트 : 버튼 추가로 새로 설정


// PET_BUTTON_GROUP
#define PET_BUTTON_GROUP_XPOS			395

// MAIN_CHAT
#define MAIN_CHAT_XPOS					570
#define MAIN_CHAT_YPOS					675 //703

// SMALL_MESSENGER
#define SMALL_MESSENGER_XPOS			570
#define SMALL_MESSENGER_YPOS			555 //583

// LARGE_MESSENGER
#define LARGE_MESSENGER_XPOS			570
#define LARGE_MESSENGER_YPOS			33 //33

// MESSENGER_CHANNEL
#define MESSENGER_CHANNEL_XPOS			570
#define MESSENGER_CHANNEL_YPOS			575

// WINDOW_VOLUME
#define WINDOW_VOLUME_XPOS				400
#define WINDOW_VOLUME_YPOS				300